authors:
  z4pf1sh:
    name: z4pf1sh
    description: Mysterious Life
    avatar: https://avatars.githubusercontent.com/u/155286196
  z4pf1sh-zh:
    name: z4pf1sh 中文
    description: 神秘生物
    avatar: https://avatars.githubusercontent.com/u/155286196
